language: java
branches:
  only:
  - master
jdk:
  - oraclejdk8
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=Build-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "BuyerRemover automated build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/JoachimVandersmissen/BuyerRemover --tags
deploy:
  provider: releases
  api_key: $TAGPERM
  file: "target/BuyerRemover.jar"
  skip_cleanup: true
  on:
    tags: false
    branch: master